#!/usr/bin/env node
'use strict';
/*
 * test_v2_trash_restore.js -- the delete confirmation's promise is kept.
 *
 * Run:  node builder/tests/test_v2_trash_restore.js
 *       node builder/tests/test_v2_trash_restore.js --headed
 *
 * THE DEFECT
 *   Deleting a report showed a confirmation that said, in so many words:
 *   "This moves {name} to the trash. You can restore it from History." Then:
 *     * the shelf's Trash rail entry opened a stub dialog reading
 *       "This screen is not available yet";
 *     * the History drawer's Trash chip rendered a hard-coded empty state --
 *       "Nothing here yet" -- whatever was actually in the trash;
 *     * and History is per-report, opened from inside a report the user can no
 *       longer open.
 *   The folder was on disk the whole time. Deleting was a one-way door
 *   carrying a written promise that it was not.
 *
 * WHAT IT ASSERTS, in a real browser, driving a real mouse
 *   1. the delete confirmation points at the place the restore actually lives,
 *      and does not point at History               (fails before the fix)
 *   2. deleting a report from the shelf, then opening Trash, LISTS it -- by
 *      name, with the path it came from            (fails before the fix)
 *   3. restoring it puts it back at its ORIGINAL path with its content intact,
 *      and it is on the shelf again with no manual refresh
 *                                                  (fails before the fix)
 *   4. restoring onto an occupied path is REFUSED, in words, and overwrites
 *      nothing                                     (fails before the fix)
 *   5. there is ONE place: History no longer offers a Trash filter it cannot
 *      fill                                        (fails before the fix)
 *
 * IT NEVER TOUCHES REAL REPORTS. The fixture is generated from scratch into the
 * OS temporary directory and the server is booted against THAT with --root.
 *
 * SKIPPING IS A FEATURE: no playwright-core (the public repository carries no
 * node_modules) or no system browser still runs the static half and exits 0.
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const net = require('node:net');
const http = require('node:http');
const { spawn } = require('node:child_process');

const HERE = __dirname;
const REPO = path.resolve(HERE, '..', '..');
const SERVER_PY = path.join(REPO, 'builder', 'web', 'server.py');
const VIEWS = path.join(REPO, 'builder', 'web', 'assets', 'v2', 'js', 'views');
const HOME_JS = path.join(VIEWS, 'home.js');
const SYNC_JS = path.join(VIEWS, 'sync.js');

const ARGS = process.argv.slice(2);
const HEADED = ARGS.includes('--headed');
const KEEP_ROOT = ARGS.includes('--keep-root');
const VIEWPORT = { width: 1440, height: 900 };

const TRASH = 'Trash';
const DELETE = 'Delete';
const MOVE_TO_TRASH = 'Move to trash';
const RESTORE = 'Restore';
const CLOSE = 'Close';

let chromium = null;
let chromiumMissing = '';
try {
  chromium = require('playwright-core').chromium;
} catch (err) {
  chromiumMissing = 'playwright-core is not installed.  npm install, then re-run.';
}

/* ------------------------------------------------------------------ *
 * the fixture
 * ------------------------------------------------------------------ */

const PROJECT_ID = '1108';
const MODULE_ID = 'CLKDIV_5G';
const DOOMED_DIR = PROJECT_ID + '/' + MODULE_ID + '/CDR';
const KEEPER_DIR = PROJECT_ID + '/' + MODULE_ID + '/PDR';
const DOOMED_TITLE = 'CLKDIV_5G CDR draft';
const KEEPER_TITLE = 'CLKDIV_5G PDR draft';
const MARKER = 'The one sentence that proves the content came back.';

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2), 'utf8');
}

function sampleReport(title, sentence) {
  return {
    template: 'sample',
    meta: { title: title, doc_no: 'DOC-1', version: 'V1.0' },
    outline: [{
      id: 'n-1',
      title: 'Overview',
      blocks: [{ type: 'para', runs: [{ t: sentence }], cardStart: true }],
      children: [],
    }],
  };
}

function buildReportsRoot(root) {
  fs.mkdirSync(root, { recursive: true });
  writeJson(path.join(root, 'templates', 'sample', 'config.json'),
    { id: 'sample', name: 'Sample template', styles: {} });
  writeJson(path.join(root, PROJECT_ID, 'project_meta.json'),
    { name: PROJECT_ID, description: 'Generated by this test' });
  writeJson(path.join(root, PROJECT_ID, MODULE_ID, 'project_meta.json'),
    { name: MODULE_ID, description: 'Divider block' });
  writeJson(path.join(root, ...DOOMED_DIR.split('/'), 'project.json'),
    sampleReport(DOOMED_TITLE, MARKER));
  writeJson(path.join(root, ...KEEPER_DIR.split('/'), 'project.json'),
    sampleReport(KEEPER_TITLE, 'Another report, never deleted.'));
  return root;
}

/* ------------------------------------------------------------------ *
 * reporting
 * ------------------------------------------------------------------ */

const failures = [];

function check(name, ok, detail) {
  console.log((ok ? '  [ok  ] ' : '  [FAIL] ') + name);
  if (!ok) {
    if (detail) console.log('         ' + detail);
    failures.push(name + (detail ? ' -- ' + detail : ''));
  }
}

function section(title) {
  console.log('');
  console.log(title);
}

/* ------------------------------------------------------------------ *
 * server lifecycle
 * ------------------------------------------------------------------ */

function freePort() {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.unref();
    probe.on('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const port = probe.address().port;
      probe.close(() => resolve(port));
    });
  });
}

function httpGet(url, timeoutMs) {
  return new Promise((resolve, reject) => {
    const req = http.get(url, (res) => { res.resume(); resolve(res.statusCode); });
    req.setTimeout(timeoutMs || 1500, () => req.destroy(new Error('timeout')));
    req.on('error', reject);
  });
}

async function waitForServer(base, child, deadlineMs) {
  const until = Date.now() + deadlineMs;
  for (;;) {
    if (child.exitCode !== null) throw new Error('the server exited before it answered');
    try {
      if (await httpGet(base + '/api/health') === 200) return;
    } catch (err) { /* not up yet */ }
    if (Date.now() > until) throw new Error('the server did not answer within ' + deadlineMs + 'ms');
    await new Promise((r) => setTimeout(r, 120));
  }
}

function startServer(root, port) {
  const python = process.env.RW_PYTHON || 'python';
  const config = path.join(root, 'templates', 'sample', 'config.json');
  const child = spawn(python, [SERVER_PY, '--port', String(port), '--root', root,
    '--config', config], { cwd: REPO, stdio: ['ignore', 'pipe', 'pipe'] });
  const log = [];
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.stdout.on('data', (c) => log.push(c));
  child.stderr.on('data', (c) => log.push(c));
  child.on('error', (err) => log.push('spawn failed: ' + err.message + '\n'));
  child.log = log;
  return child;
}

function stopServer(child) {
  if (!child || child.exitCode !== null) return Promise.resolve();
  return new Promise((resolve) => {
    child.once('exit', () => resolve());
    try { child.kill(); } catch (err) { return resolve(); }
    setTimeout(() => {
      try { child.kill('SIGKILL'); } catch (err) { /* already gone */ }
      resolve();
    }, 1000);
  });
}

/* ------------------------------------------------------------------ *
 * driving the page WITH THE MOUSE
 * ------------------------------------------------------------------ */

const settle = (page, ms) => page.waitForTimeout(ms == null ? 350 : ms);

// Every visible element whose own text (or aria-label / title) is exactly the
// wanted string. Only the innermost match is kept, so a wrapper never
// impersonates the button inside it.
function visibleTargets(page, wanted) {
  return page.evaluate((label) => {
    const norm = (s) => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
    const out = [];
    for (const el of Array.from(document.querySelectorAll('*'))) {
      const own = norm(el.innerText || el.textContent);
      const alt = norm(el.getAttribute('aria-label') || el.getAttribute('title'));
      if (own !== label && alt !== label) continue;
      const deeper = Array.from(el.querySelectorAll('*')).some((kid) => {
        const t = norm(kid.innerText || kid.textContent);
        const a = norm(kid.getAttribute('aria-label') || kid.getAttribute('title'));
        return t === label || a === label;
      });
      if (deeper) continue;
      const box = el.getBoundingClientRect();
      const style = window.getComputedStyle(el);
      if (box.width < 1 || box.height < 1) continue;
      if (style.visibility === 'hidden' || style.display === 'none') continue;
      const cx = box.x + box.width / 2;
      const cy = box.y + box.height / 2;
      const top = document.elementFromPoint(cx, cy);
      out.push({
        x: cx, y: cy,
        hittable: !!top && (top === el || el.contains(top) || top.contains(el)),
      });
    }
    return out;
  }, wanted);
}

// A real mouse press at the element's centre. No synthetic click events.
async function mouseClick(page, wanted, which) {
  const targets = await visibleTargets(page, wanted);
  const hit = targets.filter((t) => t.hittable)[which || 0];
  if (!hit) return 'nothing visible and hittable reads "' + wanted + '"';
  await page.mouse.move(hit.x, hit.y);
  await page.mouse.down();
  await page.mouse.up();
  await settle(page);
  return 'ok';
}

async function mouseClickAt(page, point) {
  await page.mouse.move(point.x, point.y);
  await page.mouse.down();
  await page.mouse.up();
  await settle(page);
}

function pageText(page) {
  return page.evaluate(() => document.body.innerText.replace(/\s+/g, ' '));
}

// The text of one region only. A toast repeats the name of what was just
// deleted, so "the trash lists it" has to be asked of the trash and of nothing
// else -- otherwise the assertion passes on the toast and proves nothing.
function textIn(page, selector) {
  return page.evaluate((sel) => {
    const el = document.querySelector(sel);
    return el ? (el.innerText || '').replace(/\s+/g, ' ') : '';
  }, selector);
}

async function waitForText(page, needle, timeoutMs) {
  const until = Date.now() + (timeoutMs == null ? 8000 : timeoutMs);
  for (;;) {
    if ((await pageText(page)).indexOf(needle) >= 0) return true;
    if (Date.now() > until) return false;
    await page.waitForTimeout(150);
  }
}

// The row-level menu glyph of one report, pressed where it really sits.
async function openRowMenu(page, title) {
  const point = await page.evaluate((wanted) => {
    const rows = Array.from(document.querySelectorAll('.rw-row'));
    const row = rows.filter((r) => (r.innerText || '').indexOf(wanted) >= 0)[0];
    if (!row) return null;
    const glyph = row.querySelector('.rw-row__actions .rw-iconbtn');
    if (!glyph) return null;
    const box = glyph.getBoundingClientRect();
    return { x: box.x + box.width / 2, y: box.y + box.height / 2 };
  }, title);
  if (!point) return 'no row reads "' + title + '"';
  await mouseClickAt(page, point);
  return 'ok';
}

/* ------------------------------------------------------------------ *
 * static checks -- these need no browser
 * ------------------------------------------------------------------ */

function staticChecks() {
  section('one place, and the confirmation points at it');
  const home = fs.readFileSync(HOME_JS, 'utf8');
  const sync = fs.readFileSync(SYNC_JS, 'utf8');

  check('the delete confirmation no longer sends the user to History',
    home.indexOf('You can restore it from History') < 0,
    'home.js still promises History');

  check('History offers no Trash filter it cannot fill',
    !/value:\s*'trash'/.test(sync),
    'sync.js still lists a trash filter chip');

  check('home.js asks the server for the trash listing',
    home.indexOf('/api/trash') >= 0,
    'home.js never calls /api/trash');

  check('home.js never names a path under the private directory',
    !/local\//.test(home));
}

/* ------------------------------------------------------------------ *
 * the run
 * ------------------------------------------------------------------ */

async function browserChecks() {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const scratch = path.join(os.tmpdir(), 'report-workbench-v2-trash', stamp);
  const reportsRoot = path.join(scratch, 'reports');
  const shots = path.join(scratch, 'screens');
  fs.mkdirSync(shots, { recursive: true });
  buildReportsRoot(reportsRoot);
  console.log('  fixture: ' + reportsRoot);

  const port = await freePort();
  const base = 'http://127.0.0.1:' + port;
  const child = startServer(reportsRoot, port);
  let browser = null;

  const cleanup = async () => {
    if (browser) await browser.close().catch(() => {});
    await stopServer(child);
    if (!KEEP_ROOT) fs.rmSync(scratch, { recursive: true, force: true });
  };

  const doomedFile = path.join(reportsRoot, ...DOOMED_DIR.split('/'), 'project.json');

  try {
    try {
      await waitForServer(base, child, 20000);
    } catch (err) {
      check('the server starts', false, err.message
        + '\n' + child.log.join('').split('\n').slice(-12).join('\n'));
      return;
    }

    try {
      browser = await chromium.launch({ channel: 'msedge', headless: !HEADED });
    } catch (err) {
      console.log('  SKIP: the system browser could not be launched.');
      console.log('        ' + String(err && err.message ? err.message : err).split('\n')[0]);
      return;
    }

    const context = await browser.newContext({ viewport: VIEWPORT });
    const page = await context.newPage();
    const consoleErrors = [];
    // The refused restore IS a 409, on purpose, and the browser logs every
    // non-2xx response as a console error of its own. That one line is the
    // network telling us the guard fired -- it is not the page faulting -- so
    // it is filtered by the request it belongs to rather than by its wording.
    page.on('console', (msg) => {
      const where = msg.location && msg.location() ? String(msg.location().url) : '';
      if (msg.type() !== 'error') return;
      if (where.indexOf('favicon') >= 0) return;
      if (where.indexOf('/api/trash-restore') >= 0) return;
      consoleErrors.push(msg.text().slice(0, 200));
    });
    page.on('pageerror', (err) => consoleErrors.push('uncaught: ' + String(err && err.message)));

    await page.goto(base + '/#/', { waitUntil: 'load' });
    await settle(page, 1200);

    /* ---- 1. the confirmation names where the restore lives ---- */

    section('1 - the delete confirmation points at the place that restores');
    let menu = await openRowMenu(page, DOOMED_TITLE);
    check('the doomed report has a row menu', menu === 'ok', menu);
    let pressed = await mouseClick(page, DELETE);
    check('the menu offers "' + DELETE + '"', pressed === 'ok', pressed);
    await settle(page, 300);
    await page.screenshot({ path: path.join(shots, '1-confirm.png') });
    const confirm = await pageText(page);
    check('the confirmation names the report it takes',
      confirm.indexOf(DOOMED_TITLE) >= 0, confirm.slice(0, 300));
    check('it does NOT send the user to History',
      confirm.indexOf('restore it from History') < 0,
      'the confirmation still reads: ' + confirm.slice(0, 300));
    check('it names ' + TRASH + ', which is where the restore is',
      confirm.indexOf('restore it from Trash') >= 0,
      'the confirmation reads: ' + confirm.slice(0, 300));

    /* ---- 2. the deleted report is LISTED in Trash ---- */

    section('2 - Trash lists what was deleted');
    pressed = await mouseClick(page, MOVE_TO_TRASH);
    check('the confirmation deletes', pressed === 'ok', pressed);
    await settle(page, 800);
    check('the report is off disk at its old path', !fs.existsSync(doomedFile));

    pressed = await mouseClick(page, TRASH);
    check('the rail offers ' + TRASH, pressed === 'ok', pressed);
    await settle(page, 700);
    await page.screenshot({ path: path.join(shots, '2-trash.png') });
    const trashText = await textIn(page, '.rw-dialog');
    check('opening ' + TRASH + ' is not a stub',
      trashText.indexOf('This screen is not available yet') < 0,
      'it still says the screen is not available');
    check(TRASH + ' lists the deleted report by name',
      trashText.indexOf(DOOMED_TITLE) >= 0,
      'Trash reads: ' + trashText.slice(0, 400));
    check('and says where it came from',
      trashText.indexOf(DOOMED_DIR) >= 0,
      'the original path is not on screen');

    /* ---- 3. restoring puts it back, intact, at its original path ---- */

    section('3 - restoring puts it back at its original path');
    pressed = await mouseClick(page, RESTORE);
    check(TRASH + ' offers "' + RESTORE + '"', pressed === 'ok', pressed);
    await settle(page, 900);
    await page.screenshot({ path: path.join(shots, '3-restored.png') });

    check('the report is back at ' + DOOMED_DIR, fs.existsSync(doomedFile));
    const restored = fs.existsSync(doomedFile)
      ? fs.readFileSync(doomedFile, 'utf8') : '';
    check('its content came back intact', restored.indexOf(MARKER) >= 0,
      'the restored document does not carry its sentence');

    await mouseClick(page, CLOSE);
    await settle(page, 700);
    const shelf = await textIn(page, '.rw-rows');
    check('it is on the shelf again with no manual refresh',
      shelf.indexOf(DOOMED_TITLE) >= 0,
      'the report table reads: ' + shelf.slice(0, 400));

    /* ---- 4. restoring onto an occupied path is refused ---- */

    section('4 - restoring onto an occupied path is refused, and overwrites nothing');
    // Delete it again, then put a DIFFERENT document back at the same path
    // behind the interface's back. The restore must refuse rather than
    // overwrite what is standing there.
    menu = await openRowMenu(page, DOOMED_TITLE);
    check('the row menu opens again', menu === 'ok', menu);
    await mouseClick(page, DELETE);
    pressed = await mouseClick(page, MOVE_TO_TRASH);
    check('it is deleted a second time', pressed === 'ok', pressed);
    await settle(page, 800);

    const OCCUPANT = 'A different report now lives here.';
    writeJson(doomedFile, sampleReport('Occupant', OCCUPANT));

    pressed = await mouseClick(page, TRASH);
    check(TRASH + ' opens', pressed === 'ok', pressed);
    await settle(page, 700);
    pressed = await mouseClick(page, RESTORE);
    check(TRASH + ' still offers "' + RESTORE + '"', pressed === 'ok', pressed);
    await settle(page, 900);
    await page.screenshot({ path: path.join(shots, '4-refused.png') });

    const refused = await textIn(page, '.rw-dialog');
    check('the refusal is in words on screen', refused.indexOf('Not restored') >= 0,
      'nothing on screen says the restore did not happen: ' + refused.slice(0, 400));
    const occupant = fs.existsSync(doomedFile)
      ? fs.readFileSync(doomedFile, 'utf8') : '';
    check('nothing was overwritten', occupant.indexOf(OCCUPANT) >= 0,
      'the occupying report is gone or changed');
    check('and the deleted one is still in the trash',
      refused.indexOf('Deleted ') >= 0,
      'the trash entry vanished with the refusal');

    /* ---- 5. one place, not two ---- */

    section('5 - History no longer offers a Trash filter it cannot fill');
    await mouseClick(page, CLOSE);
    await settle(page, 400);
    await page.goto(base + '/#/r/' + KEEPER_DIR, { waitUntil: 'load' });
    await settle(page, 1800);
    const opened = await mouseClick(page, 'History');
    if (opened === 'ok') {
      await settle(page, 700);
      await page.screenshot({ path: path.join(shots, '5-history.png') });
      const chips = await page.evaluate(() =>
        Array.from(document.querySelectorAll('.rw-drawer .rw-chip'))
          .map((c) => (c.innerText || '').trim()));
      check('the History drawer has no ' + TRASH + ' chip',
        chips.length > 0 && chips.indexOf(TRASH) < 0,
        'its chips are: ' + JSON.stringify(chips));
    } else {
      check('the History drawer opens', false, opened);
    }

    if (consoleErrors.length) {
      check('no console errors', false, consoleErrors.slice(0, 4).join(' | '));
    } else {
      console.log('  [ok  ] no console errors');
    }

    await context.close();
  } finally {
    await cleanup();
  }
}

async function main() {
  staticChecks();

  section('in a real browser');
  if (!chromium) {
    console.log('  SKIP: ' + chromiumMissing);
  } else {
    await browserChecks();
  }

  console.log('');
  if (failures.length) {
    console.log(failures.length + ' assertion(s) failed');
    process.exit(1);
  }
  console.log('all assertions passed');
  process.exit(0);
}

main().catch((err) => {
  console.log('FAIL: the harness itself failed');
  console.log(String(err && err.stack ? err.stack : err));
  process.exit(1);
});
