#!/usr/bin/env node
'use strict';
/*
 * test_v2_rename_guard.js -- /api/project-rename must never rename something
 * other than what it was asked to rename.
 *
 * Run:  node builder/tests/test_v2_rename_guard.js
 *
 * THE DEFECT
 *   A report's folder is its address, so the endpoint refuses to move it and
 *   writes meta.title instead. That rule was right, but it was implemented by
 *   falling back to the folder name when no title was sent:
 *
 *       if title is None: title = payload.get("new_name")
 *
 *   So a caller that asked ONLY for a folder rename -- the shape every other
 *   folder in the tree accepts, and the shape api.js's projectRename(dir, name)
 *   still sends -- got the report's title silently overwritten with the folder
 *   name it wanted, and a 200 whose only hint was "moved": false. Two things
 *   the caller never asked for: a title it did not choose, and a folder that
 *   did not move.
 *
 *   A request the endpoint cannot honour is refused, not rounded to the nearest
 *   thing it can do.
 *
 * WHAT IT ASSERTS
 *   1. a report + new_name + no title is REFUSED, and meta.title on disk is
 *      byte-for-byte what it was                          (fails before the fix)
 *   2. a report + title is still a title write, folder untouched, moved:false
 *   3. a report + title + new_name still writes the TITLE, not the folder name,
 *      which is the shape the old interface and the asset test both send
 *   4. a module container with new_name only still MOVES, as it always did
 *
 * NO BROWSER, NO DEPENDENCIES. This is a wire-level test of one endpoint, so it
 * runs everywhere the repository does -- which is the point: the assertion that
 * pins a data-loss rule should not be the one that skips when playwright is
 * missing.
 *
 * IT NEVER TOUCHES REAL REPORTS. The fixture is generated from scratch into the
 * OS temporary directory and the server is booted against THAT with an explicit
 * --root.
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const net = require('node:net');
const http = require('node:http');
const { spawn } = require('node:child_process');

const HERE = __dirname;
const REPO = path.resolve(HERE, '..', '..');
const SERVER_PY = path.join(REPO, 'builder', 'web', 'server.py');

const PROJECT_ID = '1108';
const MODULE_ID = 'CLKDIV_5G';
const CDR_DIR = PROJECT_ID + '/' + MODULE_ID + '/CDR';
const MODULE_DIR = PROJECT_ID + '/' + MODULE_ID;
const ORIGINAL_TITLE = MODULE_ID + ' CDR report';

/* ------------------------------------------------------------------ *
 * fixture
 * ------------------------------------------------------------------ */

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2), 'utf8');
}

function sampleReport(title) {
  return {
    template: 'sample',
    meta: { title: title, doc_no: 'DOC-1', version: 'V1.0' },
    outline: [{
      id: 'n-1',
      title: 'Overview',
      blocks: [{ type: 'para', runs: [{ t: 'First section.' }], cardStart: true }],
      children: [],
    }],
  };
}

function buildReportsRoot(root) {
  fs.mkdirSync(root, { recursive: true });
  writeJson(path.join(root, 'templates', 'sample', 'config.json'),
    { id: 'sample', name: 'Sample template', styles: {} });
  writeJson(path.join(root, PROJECT_ID, 'project_meta.json'),
    { name: 'Sample project', description: 'Generated by this test' });
  writeJson(path.join(root, PROJECT_ID, MODULE_ID, 'project_meta.json'),
    { name: MODULE_ID, description: 'Divider block' });
  writeJson(path.join(root, ...CDR_DIR.split('/'), 'project.json'),
    sampleReport(ORIGINAL_TITLE));
  return root;
}

/* ------------------------------------------------------------------ *
 * server lifecycle
 * ------------------------------------------------------------------ */

function freePort() {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.unref();
    probe.on('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const port = probe.address().port;
      probe.close(() => resolve(port));
    });
  });
}

function req(method, url, body) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const payload = body === undefined ? null : Buffer.from(JSON.stringify(body), 'utf8');
    const r = http.request({
      hostname: u.hostname,
      port: u.port,
      path: u.pathname + u.search,
      method: method,
      headers: payload
        ? { 'content-type': 'application/json', 'content-length': payload.length }
        : {},
    }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        const text = Buffer.concat(chunks).toString('utf8');
        let json = null;
        try { json = JSON.parse(text); } catch (e) { /* not JSON */ }
        resolve({ status: res.statusCode, text: text, json: json });
      });
    });
    r.on('error', reject);
    if (payload) r.write(payload);
    r.end();
  });
}

async function waitForServer(base, child, deadlineMs) {
  const until = Date.now() + deadlineMs;
  for (;;) {
    if (child.exitCode !== null) throw new Error('the server exited: ' + child.log.join(''));
    try {
      const answer = await req('GET', base + '/api/health');
      if (answer.status === 200) return;
    } catch (err) { /* not up yet */ }
    if (Date.now() > until) throw new Error('the server did not answer: ' + child.log.join(''));
    await new Promise((r) => setTimeout(r, 120));
  }
}

/* ------------------------------------------------------------------ *
 * assertions
 * ------------------------------------------------------------------ */

const results = [];
function check(name, ok, detail) {
  results.push({ name: name, ok: !!ok });
  const line = (ok ? '  [ok  ] ' : '  [FAIL] ') + name;
  console.log(detail && !ok ? line + '\n         ' + detail : line);
}

/* ------------------------------------------------------------------ *
 * main
 * ------------------------------------------------------------------ */

(async function main() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'rw-rename-guard-'));
  buildReportsRoot(root);
  const port = await freePort();
  const base = 'http://127.0.0.1:' + port;
  const child = spawn(process.env.RW_PYTHON || 'python',
    [SERVER_PY, '--port', String(port), '--root', root,
      '--config', path.join(root, 'templates', 'sample', 'config.json')],
    { cwd: REPO, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.log = [];
  child.stdout.on('data', (c) => child.log.push(c));
  child.stderr.on('data', (c) => child.log.push(c));

  const abs = (dir, ...rest) => path.join(root, ...dir.split('/'), ...rest);
  const titleOnDisk = (dir) => {
    try {
      return JSON.parse(fs.readFileSync(abs(dir, 'project.json'), 'utf8')).meta.title;
    } catch (err) {
      return 'unreadable: ' + err.message;
    }
  };

  try {
    await waitForServer(base, child, 20000);

    console.log('\na report + new_name and no title  (PIN: fails before the fix)');

    const folderOnly = await req('POST', base + '/api/project-rename',
      { dir: CDR_DIR, new_name: 'RENAMED_FOLDER' });
    check('a folder rename this endpoint cannot honour is refused',
      folderOnly.status >= 400 && folderOnly.status < 500,
      folderOnly.status + ' ' + folderOnly.text.slice(0, 200));
    check('the refusal says what to send instead',
      !!(folderOnly.json && /title/i.test(String(folderOnly.json.error || ''))),
      folderOnly.text.slice(0, 200));
    check('meta.title on disk is untouched',
      titleOnDisk(CDR_DIR) === ORIGINAL_TITLE,
      JSON.stringify(titleOnDisk(CDR_DIR)));
    check('the report folder is still at its address',
      fs.existsSync(abs(CDR_DIR, 'project.json')) &&
      !fs.existsSync(path.join(root, PROJECT_ID, MODULE_ID, 'RENAMED_FOLDER')));

    console.log('\na report + title  (the supported shape)');

    const NEW_TITLE = 'Divider close-out notes';
    const titled = await req('POST', base + '/api/project-rename',
      { dir: CDR_DIR, title: NEW_TITLE });
    check('renaming a report answers with the SAME dir and moved:false',
      titled.status === 200 && titled.json && titled.json.dir === CDR_DIR &&
      titled.json.moved === false,
      titled.status + ' ' + titled.text.slice(0, 200));
    check('the title is written', titleOnDisk(CDR_DIR) === NEW_TITLE,
      JSON.stringify(titleOnDisk(CDR_DIR)));
    check('the report folder still has not moved',
      fs.existsSync(abs(CDR_DIR, 'project.json')));

    console.log('\na report + title + new_name  (what the old interface sends)');

    const BOTH_TITLE = 'Divider close-out notes, second pass';
    const both = await req('POST', base + '/api/project-rename',
      { dir: CDR_DIR, new_name: 'STILL_NOT_A_FOLDER_RENAME', title: BOTH_TITLE });
    check('the title wins and the folder is left alone',
      both.status === 200 && both.json && both.json.moved === false &&
      titleOnDisk(CDR_DIR) === BOTH_TITLE &&
      !fs.existsSync(path.join(root, PROJECT_ID, MODULE_ID, 'STILL_NOT_A_FOLDER_RENAME')),
      both.status + ' ' + both.text.slice(0, 200) + ' title=' +
      JSON.stringify(titleOnDisk(CDR_DIR)));

    console.log('\na module container  (every other endpoint behaviour is untouched)');

    const movedModule = await req('POST', base + '/api/project-rename',
      { dir: MODULE_DIR, new_name: 'CLKDIV_6G' });
    const moved = movedModule.json && movedModule.json.dir === PROJECT_ID + '/CLKDIV_6G' &&
      fs.existsSync(path.join(root, PROJECT_ID, 'CLKDIV_6G', 'CDR', 'project.json'));
    check('renaming a MODULE with new_name only still moves the folder', moved,
      movedModule.status + ' ' + movedModule.text.slice(0, 200));
  } catch (err) {
    check('the test ran to the end', false, err && err.stack ? err.stack : String(err));
  } finally {
    child.kill();
    try { fs.rmSync(root, { recursive: true, force: true }); } catch (err) { /* windows */ }
  }

  const failed = results.filter((r) => !r.ok);
  console.log('\n' + (results.length - failed.length) + '/' + results.length + ' checks passed');
  if (failed.length) {
    console.log('FAILED: ' + failed.map((r) => r.name).join(' | '));
    process.exit(1);
  }
  console.log('rename guard: all checks passed');
})().catch((err) => {
  console.error(err && err.stack ? err.stack : err);
  process.exit(1);
});
