#!/usr/bin/env node
'use strict';
/*
 * test_v2_restart_flush.js -- "Pull and restart" must not restart on top of an
 * edit that is only in the page.
 *
 * Run:  node builder/tests/test_v2_restart_flush.js
 *       node builder/tests/test_v2_restart_flush.js --headed     (watch it work)
 *
 * THE DEFECT
 *   Every other server-side action on the exchange screen flushes the pending
 *   save before it runs, because each one reads or replaces project.json on
 *   disk. The tool-version control did not: it called window.location.reload()
 *   straight from its onClick. An edit typed inside the autosave debounce was
 *   therefore thrown away by the restart -- not saved, not snapshotted, and not
 *   in History, because the snapshot the server takes is a copy of the file the
 *   edit never reached.
 *
 * WHAT IT ASSERTS, in a real browser, against what lands on disk
 *   1. an edit made a moment before the restart is ON DISK afterwards
 *      (before the fix: the reload wins the race and the edit is gone)
 *   2. when the document CANNOT be written, the restart does not happen: the
 *      page is still the page it was, the screen says why, and the edit is
 *      still in memory rather than discarded by a reload
 *      (before the fix: it reloaded regardless and the edit went with it)
 *
 * The edit is made through the store rather than by typing, so that it is
 * pending at the exact instant the control is pressed -- the state under test
 * is "a save is owed", and typing it would spend the debounce window this test
 * is about.
 *
 * IT NEVER TOUCHES REAL REPORTS. The fixture is generated from scratch into the
 * OS temporary directory and the server is booted against THAT with an explicit
 * --root, exactly as the other v2 browser tests do.
 *
 * SKIPPING IS A FEATURE. The public repository carries no node_modules, so a
 * missing playwright-core exits 0 with one line.
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const net = require('node:net');
const http = require('node:http');
const { spawn } = require('node:child_process');

const HERE = __dirname;
const REPO = path.resolve(HERE, '..', '..');
const SERVER_PY = path.join(REPO, 'builder', 'web', 'server.py');
const HEADED = process.argv.includes('--headed');

let chromium = null;
try {
  chromium = require('playwright-core').chromium;
} catch (err) {
  console.log('SKIP: playwright-core is not installed (npm install to run this file).');
  process.exit(0);
}

const PROJECT_ID = '1108';
const MODULE_ID = 'CLKDIV_5G';
const CDR_DIR = PROJECT_ID + '/' + MODULE_ID + '/CDR';
const START_TEXT = 'First section, as it was saved.';
const EDIT_ONE = 'First section, edited a moment before the restart.';
const EDIT_TWO = 'First section, edited while the disk was refusing writes.';

/* ------------------------------------------------------------------ *
 * fixture
 * ------------------------------------------------------------------ */

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2), 'utf8');
}

function sampleReport() {
  return {
    template: 'sample',
    meta: { title: MODULE_ID + ' CDR report', doc_no: 'DOC-1', version: 'V1.0' },
    outline: [
      {
        id: 'n-1',
        title: 'Overview',
        blocks: [{ type: 'para', runs: [{ t: START_TEXT }], cardStart: true }],
        children: [],
      },
      {
        id: 'n-2',
        title: 'Design description',
        blocks: [{ type: 'para', runs: [{ t: 'Second section.' }], cardStart: true }],
        children: [],
      },
    ],
  };
}

function sampleTemplateConfig() {
  return {
    id: 'sample',
    name: 'Sample template',
    caption_prefix: { figure: 'Figure', table: 'Table' },
    toc: { enabled: true },
    skeleton: [{ title: 'Overview', children: [] }, { title: 'Design description', children: [] }],
    cover: { secrecy_default: 'Internal' },
    styles: {},
    compliance: {
      axis_labels: ['MIN', 'TYP', 'MAX', 'NTWC'],
      setting_kinds: ['common_setting', 'module_setting', 'tb'],
      default_limit: {},
      flag_color: 'FF0000',
      col_w_cm: { cat: 2.4, item: 3.6, unit: 1.4 },
      fills: { header: 'FFF2CC', setting: 'F2EFE9', result: 'FFFFFF' },
    },
    free_table: { header_fill: 'FFF2CC' },
    ui_strings: {},
    table_presets: [],
  };
}

function buildReportsRoot(root) {
  fs.mkdirSync(root, { recursive: true });
  writeJson(path.join(root, 'templates', 'sample', 'config.json'), sampleTemplateConfig());
  writeJson(path.join(root, PROJECT_ID, 'project_meta.json'),
    { name: 'Sample project', description: 'Generated by this test' });
  writeJson(path.join(root, PROJECT_ID, MODULE_ID, 'project_meta.json'),
    { name: MODULE_ID, description: 'Divider block' });
  writeJson(path.join(root, ...CDR_DIR.split('/'), 'project.json'), sampleReport());
  return root;
}

/* ------------------------------------------------------------------ *
 * server lifecycle
 * ------------------------------------------------------------------ */

function freePort() {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.unref();
    probe.on('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const port = probe.address().port;
      probe.close(() => resolve(port));
    });
  });
}

function req(method, url) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const r = http.request({
      hostname: u.hostname, port: u.port, path: u.pathname + u.search, method: method,
    }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve({ status: res.statusCode, text: Buffer.concat(chunks).toString('utf8') }));
    });
    r.on('error', reject);
    r.end();
  });
}

async function waitForServer(base, child, deadlineMs) {
  const until = Date.now() + deadlineMs;
  for (;;) {
    if (child.exitCode !== null) throw new Error('the server exited: ' + child.log.join(''));
    try {
      const answer = await req('GET', base + '/api/health');
      if (answer.status === 200) return;
    } catch (err) { /* not up yet */ }
    if (Date.now() > until) throw new Error('the server did not answer: ' + child.log.join(''));
    await new Promise((r) => setTimeout(r, 120));
  }
}

/* ------------------------------------------------------------------ *
 * assertions
 * ------------------------------------------------------------------ */

const results = [];
function check(name, ok, detail) {
  results.push({ name: name, ok: !!ok });
  const line = (ok ? '  [ok  ] ' : '  [FAIL] ') + name;
  console.log(detail && !ok ? line + '\n         ' + detail : line);
}

const wait = (ms) => new Promise((r) => setTimeout(r, ms));

/* ------------------------------------------------------------------ *
 * browser helpers
 * ------------------------------------------------------------------ */

// The exchange drawer only enables the control when there is an update to pull,
// and /api/version reports none on a machine with no updater. The state is set
// through the store the interface itself reads, so the button under test is the
// real one in its real enabled state.
const OFFER_UPDATE = `(async () => {
  const { store } = await import('/assets/v2/js/store.js');
  store.set({ version: { local: '2.0.0', available: '2.0.1', needsRestart: true,
                         changes: ['one fix'] } });
})()`;

// Make an edit and press the control in ONE synchronous step, so the autosave
// debounce cannot land it by luck.
function editAndRestart(text) {
  return `(async () => {
    const { store } = await import('/assets/v2/js/store.js');
    const project = store.get().project;
    project.outline[0].blocks[0].runs[0].t = ${JSON.stringify(text)};
    store.markDirty();
    const button = Array.from(document.querySelectorAll('button'))
      .filter((b) => b.textContent.trim() === 'Pull and restart')[0];
    if (!button) return 'no button';
    if (button.disabled) return 'button disabled';
    window.__rwSurvived = 1;
    button.click();
    return 'clicked';
  })()`;
}

// Refuse every write of the document, and nothing else.
const BLOCK_SAVES = `(() => {
  const real = window.fetch;
  window.fetch = function (input, init) {
    const url = String((input && input.url) || input || '');
    const method = String((init && init.method) || 'GET').toUpperCase();
    if (method === 'PUT' && url.indexOf('/api/project') !== -1) {
      return Promise.reject(new TypeError('Failed to fetch'));
    }
    return real.apply(window, arguments);
  };
})()`;

/* ------------------------------------------------------------------ *
 * main
 * ------------------------------------------------------------------ */

(async function main() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'rw-restart-flush-'));
  buildReportsRoot(root);
  const port = await freePort();
  const base = 'http://127.0.0.1:' + port;
  const child = spawn(process.env.RW_PYTHON || 'python',
    [SERVER_PY, '--port', String(port), '--root', root,
      '--config', path.join(root, 'templates', 'sample', 'config.json')],
    { cwd: REPO, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.log = [];
  child.stdout.on('data', (c) => child.log.push(c));
  child.stderr.on('data', (c) => child.log.push(c));

  const projectFile = path.join(root, ...CDR_DIR.split('/'), 'project.json');
  const firstParagraph = () => {
    try {
      return JSON.parse(fs.readFileSync(projectFile, 'utf8')).outline[0].blocks[0].runs[0].t;
    } catch (err) {
      return 'unreadable: ' + err.message;
    }
  };

  let browser = null;
  try {
    await waitForServer(base, child, 20000);

    browser = await chromium.launch({ channel: 'msedge', headless: !HEADED });
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const page = await context.newPage();

    const editorUrl = base + '/#/r/' + CDR_DIR.split('/').map(encodeURIComponent).join('/');
    const openExchange = async () => {
      await page.goto(editorUrl, { waitUntil: 'load' });
      await wait(1200);
      await page.evaluate(OFFER_UPDATE);
      await page.click('[title="Text exchange"]');
      await wait(1200);
      await page.evaluate(OFFER_UPDATE);   // the drawer may have mounted first
      await wait(200);
      const seen = await page.evaluate(
        () => Array.from(document.querySelectorAll('button')).map((b) => b.textContent.trim()));
      if (seen.indexOf('Pull and restart') === -1) {
        throw new Error('the exchange drawer did not open: ' + JSON.stringify(seen.slice(0, 20)));
      }
    };

    console.log('\nan edit made a moment before the restart  (PIN: fails before the fix)');

    await openExchange();
    const clicked = await page.evaluate(editAndRestart(EDIT_ONE));
    check('the control was pressed while a save was owed', clicked === 'clicked', String(clicked));
    await wait(4000);
    check('the edit is on disk after the restart',
      firstParagraph() === EDIT_ONE, JSON.stringify(firstParagraph()));
    check('the page did restart', await page.evaluate(() => window.__rwSurvived === undefined));

    // Put the document back, so the second half starts from a known file.
    writeJson(projectFile, sampleReport());

    console.log('\nthe document cannot be written  (PIN: fails before the fix)');

    await openExchange();
    await page.evaluate(BLOCK_SAVES);
    const clicked2 = await page.evaluate(editAndRestart(EDIT_TWO));
    check('the control was pressed again', clicked2 === 'clicked', String(clicked2));
    await wait(8000);
    check('the page did NOT restart on top of the unsaved edit',
      await page.evaluate(() => window.__rwSurvived === 1));
    const body = await page.evaluate(() => String(document.body.innerText || ''));
    check('the screen says the restart was held back',
      /Not restarted/i.test(body) && /not saved/i.test(body),
      body.slice(0, 400).replace(/\s+/g, ' '));
    check('the edit is still in the page rather than discarded',
      await page.evaluate((t) => {
        const el = document.querySelector('.rw-app');
        return !!el && String(el.innerText || '').indexOf(t) !== -1;
      }, EDIT_TWO));
    check('nothing was written to disk while writes were refused',
      firstParagraph() === START_TEXT, JSON.stringify(firstParagraph()));
  } catch (err) {
    check('the test ran to the end', false, err && err.stack ? err.stack : String(err));
  } finally {
    if (browser) { try { await browser.close(); } catch (err) { /* closing */ } }
    child.kill();
    await wait(200);
    try { fs.rmSync(root, { recursive: true, force: true }); } catch (err) { /* windows */ }
  }

  const failed = results.filter((r) => !r.ok);
  console.log('\n' + (results.length - failed.length) + '/' + results.length + ' checks passed');
  if (failed.length) {
    console.log('FAILED: ' + failed.map((r) => r.name).join(' | '));
    process.exit(1);
  }
  console.log('restart flush: all checks passed');
})().catch((err) => {
  console.error(err && err.stack ? err.stack : err);
  process.exit(1);
});
